version: '3.8'

services:
  db:
    image: mysql:8
    container_name: mysql-db
    env_file:
      - .env
    restart: always
    environment:
      MYSQL_DATABASE:  ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: 
      context: ./UniHub_backend
      dockerfile: Dockerfile
    container_name: django-app
    env_file:
      - .env
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - .:/app
    working_dir: /app/UniHub_backend
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py shell < create_superuser.py &&
             python manage.py runserver 0.0.0.0:8000"
  notification:
    build:
      context: ./notification_service
      dockerfile: Dockerfile
    container_name: notification-service
    env_file:
      - .env
    restart: always
    ports:
      - "8001:8001"
    environment:
      SENDGRID_API_KEY: ${SENDGRID_API_KEY}

volumes:
  mysql_data:
