version: '3.8'

services:
  db:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_DATABASE: thedb
      MYSQL_USER: rootUser
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootPassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build: .
    container_name: django-app
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=mydatabase
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_HOST=db
    volumes:
      - .:/app

volumes:
  mysql_data:
