# Generated by Django 5.1.7 on 2025-03-13 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_comment_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.TextField(blank=True, null=True),
        ),
    ]
